---
efiMountPoints:
    - fsType: vfat
      options: "umask=0077"

mountOptions:
    default: "defaults,noatime"
    zfs:     "defaults"
    btrfs:   "defaults,noatime,compress=zstd"
    f2fs:    "defaults,noatime"
    fat:     "defaults,noatime"
    fat32:   "defaults,noatime"
    ext2:    "defaults,noatime"
    ext3:    "defaults,noatime"
    ext4:    "defaults,noatime"
    nfs:     "defaults,noatime"
    ntfs:    "defaults,noatime"
    xfs:     "defaults,noatime"
