---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 300M
efiSystemPartitionName: "EFI"

userSwapChoices:
    - none
    - small
    - suspend

defaultFileSystemType: "ext4"

availableFileSystemTypes: [ "ext4", "btrfs", "xfs" ]

partitionLayout:
    - name: "root"
      filesystem: "unknown"
      mountPoint: "/"
      size: 100%

drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
enableLuksAutomatedPartitioning: true

initialPartitioningChoice: erase
initialSwapChoice: none
