---
defaultGroups:
    - users
    - sudo
    - audio
    - video
    - plugdev
    - netdev

autologinGroup: autologin
doAutologin: false

sudoersGroup: sudo
setRootPassword: true
doReusePassword: false

passwordRequirements:
    minLength: 4
    maxLength: -1

allowWeakPasswords: true
allowWeakPasswordsDefault: false

userShell: "/bin/bash"

hostname:
    location: EtcHostname
    writeHostsFile: true
