# Vertex Linux — Calamares main settings.
# See: https://github.com/calamares/calamares/blob/calamares/settings.conf
---
modules-search: [ local ]

instances:
- id:       rootfs
  module:   unpackfs
  config:   unpackfs.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - initramfscfg
  - grubcfg
  - bootloader
  - displaymanager
  - removeuser
  - umount
- show:
  - finished

branding: vertex

prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end: false
